// ─────────────────────────────────────────────────────────────
//  Marketplace seed: 50 solo agents + 50 teams
//  Owned by a single "system" user (id = sys_marketplace_seed) so they
//  appear in the public Agent Store. Idempotent — runs at boot, only
//  creates listings whose deterministic listing_id ('ls_seed_<slug>')
//  isn't already saved.
// ─────────────────────────────────────────────────────────────

const crypto = require('crypto');

// ── Solo agent specs (50) ──
//   av:    avatar emoji
//   slug:  used as listing_id ('ls_seed_<slug>')
//   nm:    title / agent name
//   cat:   marketplace category (sales|marketing|research|writing|ops|other)
//   sk:    1–3 skill ids
//   hire:  Hired-for line (one sentence)
//   duties:Day-to-day line (1–2 sentences)
//   desc:  Listing description (90–250 chars)
//   tags:  marketplace tag ids (optional)
//   demos: 0–3 demo prompts
//   price: JPY (0 = free)
//   uses:  uses_count to seed
//   rating:1.0–5.0
//   reviews: rating_count
//   ribbon:'hot' | 'new' | undefined
const SEED_AGENTS = [
  // ── SALES (8) ──
  { av:'📩', slug:'outbound-cold', nm:'Cold Outbound Pro', cat:'sales', sk:['writing','marketing','support'],
    hire:'Open conversations with cold prospects who actually reply.',
    duties:'Research each lead, write a 3-line opener that references something specific, then 2 follow-ups spaced 3 days apart.',
    desc:'Researches the lead, writes a personalized opener, and queues a 2-step follow-up. Built for B2B SaaS outbound that gets replies.',
    tags:['sales','b2b'], demos:['Write a cold opener for a CMO at an e-commerce company','Draft a 2-step follow-up sequence'],
    price:2400, uses:1840, rating:4.8, reviews:87, ribbon:'hot' },
  { av:'📞', slug:'inbound-qualifier', nm:'Inbound Qualifier', cat:'sales', sk:['analysis','support'],
    hire:'Qualify inbound leads in under a minute.',
    duties:'Score the lead against ICP, ask 3 disqualifying questions, hand off to AE if hot.',
    desc:'Pull the lead, score against ICP, ask 3 disqualifying questions, hand off if hot. Saves AEs from junk calls.',
    tags:['sales','crm'], demos:['Qualify this lead based on company size and use case'],
    price:1900, uses:920, rating:4.7, reviews:54 },
  { av:'🎬', slug:'demo-prep', nm:'Demo Prep AI', cat:'sales', sk:['research','planning','writing'],
    hire:'Prep a personalized demo in 30 seconds.',
    duties:'Read the prospect, pull their public stack, write talking points + 5 likely objections with answers.',
    desc:'Pulls a prospect summary + 5 likely objections + matching talking points before every call. Never wing a demo again.',
    tags:['sales','demo'], demos:['Prep a demo for Acme Corp; we sell observability'],
    price:2900, uses:540, rating:4.9, reviews:38 },
  { av:'💬', slug:'follow-up-closer', nm:'Follow-up Closer', cat:'sales', sk:['writing','support'],
    hire:'Re-engage stalled deals without sounding desperate.',
    duties:'Read thread context, suggest 3 angles (value reminder, social proof, deadline), draft each.',
    desc:'Drafts re-engagement emails with 3 different angles (value, social proof, deadline). Pick one and ship.',
    tags:['sales','email'], demos:['The deal went quiet 2 weeks ago — bring it back'],
    price:1500, uses:2100, rating:4.6, reviews:142, ribbon:'hot' },
  { av:'💰', slug:'price-negotiator', nm:'Pricing Negotiator', cat:'sales', sk:['analysis','planning','writing'],
    hire:'Push back on discount requests without losing the deal.',
    duties:'Analyze the ask, suggest a counter (value-add over discount), draft the email.',
    desc:'Analyzes pricing pushback, recommends a counter that protects margin (value-add over straight discount), drafts the reply.',
    tags:['sales'], demos:['Customer asked for 30% off — counter without losing them'],
    price:2900, uses:412, rating:4.8, reviews:29 },
  { av:'📜', slug:'proposal-writer', nm:'Proposal Writer', cat:'sales', sk:['writing','planning'],
    hire:'Turn a discovery call into a clean proposal.',
    duties:'Read the call notes, structure into Problem / Solution / Pricing / Next Steps.',
    desc:'Take messy discovery notes and turn them into a polished 1-page proposal in your brand voice.',
    tags:['sales','docs'], demos:['Build a proposal from these notes'],
    price:2400, uses:680, rating:4.7, reviews:56 },
  { av:'📊', slug:'account-mapper', nm:'Account Mapper', cat:'sales', sk:['research','analysis'],
    hire:'Map an enterprise org chart and find the right entry point.',
    duties:'Pull LinkedIn + press, find decision makers, suggest entry point + reference connection.',
    desc:'Maps the buying committee at large accounts, finds your warmest path in. Stops "I can\'t find the right person" cold.',
    tags:['sales','b2b'], demos:['Map the marketing org at a Fortune 500 retailer'],
    price:3900, uses:248, rating:4.9, reviews:21, ribbon:'new' },
  { av:'🛎️', slug:'win-loss-analyst', nm:'Win/Loss Analyst', cat:'sales', sk:['analysis','research'],
    hire:'Run win/loss interviews and surface why deals slip.',
    duties:'Generate the interview script, summarize calls, tag patterns across recent losses.',
    desc:'Turns post-deal interviews into a pattern analysis. Highlights the 3 reasons you keep losing and how to fix it.',
    tags:['sales','research'], demos:['Analyze these 5 lost deals'],
    price:0, uses:312, rating:4.7, reviews:31 },

  // ── MARKETING (12) ──
  { av:'✍️', slug:'seo-blog-writer', nm:'SEO Blog Writer Pro', cat:'marketing', sk:['writing','research'],
    hire:'Write SEO-optimized blog posts that actually rank.',
    duties:'Keyword research → SERP analysis → outline → 1500-word draft → internal links → rewrite pass.',
    desc:'Pro-grade SEO writing in your brand voice. Keyword research, SERP analysis, outline, draft, internal links, rewrite — one prompt away.',
    tags:['seo','blog','writing'], demos:['Write a 1500-word post on "best CRMs for startups"'],
    price:2400, uses:3200, rating:4.8, reviews:184, ribbon:'hot' },
  { av:'🐦', slug:'twitter-autopilot', nm:'X (Twitter) Autopilot', cat:'marketing', sk:['marketing','sns','writing'],
    hire:'Run a Twitter account that grows organically.',
    duties:'Spot trending topics in your niche, write engaging hooks, schedule the day.',
    desc:'Trend mining + hook design + scheduled posting. Grow X without spending hours every day on the timeline.',
    tags:['twitter','sns'], demos:['Plan today\'s tweet schedule for a SaaS founder'],
    price:1500, uses:2890, rating:4.8, reviews:121 },
  { av:'📱', slug:'tiktok-scripter', nm:'TikTok Scripter', cat:'marketing', sk:['writing','sns','marketing'],
    hire:'Write TikTok / Reels scripts built for virality.',
    duties:'Trend mining + hook design + script + CTA + iterate.',
    desc:'Built for short-form virality, fed by current trends. Hook + script + CTA every time.',
    tags:['tiktok','sns','video'], demos:['Write a 30-second hook for a productivity app'],
    price:1900, uses:1320, rating:4.7, reviews:96, ribbon:'hot' },
  { av:'🎯', slug:'ad-copy-writer', nm:'Ad Copy Writer', cat:'marketing', sk:['writing','marketing'],
    hire:'Write 10 high-CTR ad variants in 60 seconds.',
    duties:'Hook + body + CTA × multiple angles (pain, gain, social proof, urgency).',
    desc:'Generates 10 ad variants per ask, each with a different angle. Pick the winner; ship the rest as A/B set.',
    tags:['ads','copy'], demos:['Write 10 Facebook ad variants for a meal kit service'],
    price:2900, uses:1180, rating:4.8, reviews:74 },
  { av:'📅', slug:'content-calendar', nm:'Content Calendar AI', cat:'marketing', sk:['planning','marketing','sns'],
    hire:'Plan a 30-day content calendar across all channels.',
    duties:'Mix evergreen + trending + promotional, balance channels, suggest visuals.',
    desc:'Builds a 30-day content plan across X, IG, TikTok, blog, email — balanced for evergreen, trending, and promotional.',
    tags:['content','planning'], demos:['Plan a 30-day calendar for a coffee subscription brand'],
    price:1900, uses:760, rating:4.7, reviews:48 },
  { av:'📧', slug:'email-campaigns', nm:'Email Campaign Pro', cat:'marketing', sk:['writing','marketing'],
    hire:'Write conversion-focused email campaigns.',
    duties:'Subject lines (5 options) + preheader + body + CTA, plus 2-step follow-up.',
    desc:'Five subject options + preheader + body + CTA + a 2-step follow-up. Built for newsletters and promos that get clicked.',
    tags:['email','marketing'], demos:['Write a Black Friday email for a fashion brand'],
    price:1900, uses:1450, rating:4.8, reviews:88 },
  { av:'🏷️', slug:'brand-strategist', nm:'Brand Strategist', cat:'marketing', sk:['planning','marketing','idea'],
    hire:'Define a brand voice, positioning, and messaging matrix.',
    duties:'Tone of voice, audience archetypes, messaging matrix, sample copy.',
    desc:'Builds a tone-of-voice doc + audience archetypes + a messaging matrix you can hand to anyone on the team.',
    tags:['brand','strategy'], demos:['Define the brand for a sustainable activewear startup'],
    price:4900, uses:312, rating:4.9, reviews:24, ribbon:'new' },
  { av:'📰', slug:'pr-pitcher', nm:'PR Pitcher', cat:'marketing', sk:['writing','research','marketing'],
    hire:'Pitch your launch to journalists who actually cover your space.',
    duties:'Find relevant journalists, draft a personalized pitch each, follow up.',
    desc:'Identifies the 10 right journalists for your launch, drafts a personalized pitch each, queues a single follow-up.',
    tags:['pr','press'], demos:['Pitch a launch in the climate-tech beat'],
    price:3900, uses:212, rating:4.7, reviews:18 },
  { av:'🎨', slug:'landing-page-writer', nm:'Landing Page Writer', cat:'marketing', sk:['writing','marketing'],
    hire:'Write landing-page copy that converts visitors to signups.',
    duties:'Hero + benefits + social proof + objections + final CTA, conversion-tuned.',
    desc:'Conversion-focused landing copy. Hero + benefits + social proof + objections + closing CTA, all in your brand voice.',
    tags:['landing','copy'], demos:['Write the homepage for a habit tracker SaaS'],
    price:2400, uses:920, rating:4.8, reviews:62 },
  { av:'📡', slug:'social-trends', nm:'Social Trend Spotter', cat:'marketing', sk:['research','sns','marketing'],
    hire:'Surface 5 fresh content angles every morning.',
    duties:'Monitor X / TikTok / Reddit, return the most relevant trends + post hooks.',
    desc:'Daily trend digest tuned to your niche. Each morning: 5 trends + matching content hooks ready to ship.',
    tags:['trends','sns'], demos:['What\'s trending in the personal finance space today?'],
    price:1500, uses:1620, rating:4.6, reviews:103 },
  { av:'🎤', slug:'podcast-promoter', nm:'Podcast Promoter', cat:'marketing', sk:['marketing','sns','writing'],
    hire:'Promote a new episode across every channel.',
    duties:'Pull soundbites, write tweets, IG captions, LinkedIn post, newsletter blurb.',
    desc:'One podcast episode in → tweets, IG captions, LinkedIn post, newsletter blurb out. All in your show\'s voice.',
    tags:['podcast','sns'], demos:['Promote episode 47 of a startup podcast'],
    price:1900, uses:340, rating:4.7, reviews:22 },
  { av:'💌', slug:'newsletter-creator', nm:'Newsletter Writer', cat:'marketing', sk:['writing','research','marketing'],
    hire:'Ship a weekly newsletter your subscribers actually open.',
    duties:'Curate the week\'s top stories, write the intro + sections + outro, clean subject line.',
    desc:'Curates the week, writes a punchy intro and 3 sections, lands on a subject line that gets opened.',
    tags:['newsletter','email'], demos:['Write this week\'s issue on AI productivity'],
    price:0, uses:2200, rating:4.8, reviews:144 },

  // ── RESEARCH (8) ──
  { av:'🔍', slug:'competitor-analyst', nm:'Competitor Analyst', cat:'research', sk:['research','analysis'],
    hire:'Map a competitive landscape and find the gap.',
    duties:'Pull each competitor\'s features, pricing, positioning. Surface where to play.',
    desc:'Pulls features, pricing, positioning across competitors. Highlights the underserved niche you should target.',
    tags:['competitor','research'], demos:['Map the project management tool space and find a wedge'],
    price:3900, uses:480, rating:4.9, reviews:36, ribbon:'hot' },
  { av:'📈', slug:'market-research', nm:'Market Research AI', cat:'research', sk:['research','analysis'],
    hire:'Research a market in 5 minutes instead of 5 days.',
    duties:'Market size, growth, trends, key players, customer segments, opportunities.',
    desc:'Compresses a week of analyst work into 5 minutes. Market size, growth, trends, key players, customer segments.',
    tags:['research','market'], demos:['Research the smart-home accessory market'],
    price:2900, uses:680, rating:4.8, reviews:51 },
  { av:'🧪', slug:'patent-researcher', nm:'Patent Researcher', cat:'research', sk:['research','analysis','translate'],
    hire:'Search patents, summarize claims, flag conflicts.',
    duties:'Search relevant filings, summarize key claims, flag potential conflicts with your idea.',
    desc:'Searches relevant patent filings, summarizes the key claims, flags potential conflicts. Useful before any technical launch.',
    tags:['patent','legal'], demos:['Search prior art for a magnetic phone mount design'],
    price:4900, uses:84, rating:4.7, reviews:8 },
  { av:'📚', slug:'academic-reader', nm:'Academic Paper Reader', cat:'research', sk:['research','analysis','teaching'],
    hire:'Summarize a 30-page paper in 5 minutes.',
    duties:'TL;DR + methodology + findings + limitations + citation-ready quotes.',
    desc:'TL;DR + methodology + findings + limitations + citation-ready quotes. Built for grad students and journalists.',
    tags:['academic','research'], demos:['Summarize this paper on RLHF'],
    price:1500, uses:1420, rating:4.8, reviews:72 },
  { av:'🏭', slug:'industry-analyst', nm:'Industry Analyst', cat:'research', sk:['research','analysis','planning'],
    hire:'Get a McKinsey-grade brief on any industry.',
    duties:'Industry structure, value chain, profit pools, disruption vectors, key players.',
    desc:'McKinsey-style industry brief: structure, value chain, profit pools, disruption vectors, key players. In 10 minutes.',
    tags:['industry','strategy'], demos:['Brief me on the EV charging industry'],
    price:4900, uses:212, rating:4.9, reviews:18 },
  { av:'🧑‍🤝‍🧑', slug:'persona-builder', nm:'Persona Builder', cat:'research', sk:['research','analysis','idea'],
    hire:'Build customer personas from interviews + data.',
    duties:'Cluster interviews into 3 personas with goals, frustrations, jobs-to-be-done.',
    desc:'Clusters customer interviews into 3 actionable personas. Goals, frustrations, jobs-to-be-done, perfect-day quotes.',
    tags:['persona','ux'], demos:['Build personas from these 8 interviews'],
    price:2400, uses:380, rating:4.7, reviews:31 },
  { av:'📡', slug:'trend-spotter', nm:'Trend Spotter', cat:'research', sk:['research','analysis','idea'],
    hire:'Spot emerging trends in your industry weekly.',
    duties:'Scan signals across forums, Twitter, news. Return 5 trends with conviction levels.',
    desc:'Weekly digest of the 5 most-likely-to-matter trends in your industry, each with a conviction level and reasoning.',
    tags:['trends','signal'], demos:['What\'s emerging in B2B fintech this week?'],
    price:0, uses:2140, rating:4.7, reviews:128 },
  { av:'🕵️', slug:'data-investigator', nm:'Data Investigator', cat:'research', sk:['analysis','research'],
    hire:'Find the story buried in your dataset.',
    duties:'Explore the data, surface the 3 most interesting patterns, draft the narrative.',
    desc:'Throw a dataset at it; get back the 3 most interesting patterns plus a draft narrative. Ideal for blog data stories.',
    tags:['data','analysis'], demos:['Find the story in this Stripe revenue data'],
    price:2900, uses:520, rating:4.8, reviews:42 },

  // ── WRITING (10) ──
  { av:'📖', slug:'storyteller', nm:'Brand Storyteller', cat:'writing', sk:['writing','idea'],
    hire:'Tell your origin story so it sticks.',
    duties:'Brand origin → key moments → values → today, in narrative form (not bullet points).',
    desc:'Turns "we started in 2020 because..." into a story people remember. About-page magic, in your voice.',
    tags:['brand','story'], demos:['Tell our origin story for the About page'],
    price:1900, uses:540, rating:4.9, reviews:38 },
  { av:'📝', slug:'tech-doc-writer', nm:'Tech Doc Writer', cat:'writing', sk:['writing','coding'],
    hire:'Write developer docs that don\'t suck.',
    duties:'Examples-first, copy-pasteable code, gotchas spelled out. README + Quickstart + API ref.',
    desc:'Examples-first, copy-pasteable code, gotchas called out. README + Quickstart + reference, all coherent.',
    tags:['docs','dev'], demos:['Write the README for an API client library'],
    price:2900, uses:1180, rating:4.9, reviews:78 },
  { av:'✏️', slug:'editor-pro', nm:'Editor Pro', cat:'writing', sk:['writing','analysis'],
    hire:'Edit any draft to a higher gear.',
    duties:'Tighten + sharpen voice + flag fluff + suggest restructures. Tracks changes inline.',
    desc:'Tightens prose, sharpens voice, flags fluff, suggests restructures. Like having a senior editor review every draft.',
    tags:['editing','writing'], demos:['Edit this 1200-word essay for tightness'],
    price:1500, uses:2840, rating:4.8, reviews:182, ribbon:'hot' },
  { av:'🌍', slug:'translator-pro', nm:'JA↔EN Translator', cat:'writing', sk:['translate','writing'],
    hire:'Translate marketing copy with brand voice intact.',
    duties:'JA↔EN translation that preserves nuance + brand tone, not just literal.',
    desc:'Translates marketing/product copy in either direction. Preserves brand voice and nuance — not literal, not stiff.',
    tags:['translation','i18n'], demos:['Translate this product description from JA to EN'],
    price:1500, uses:1620, rating:4.8, reviews:114 },
  { av:'📰', slug:'headline-generator', nm:'Headline Generator', cat:'writing', sk:['writing','marketing','idea'],
    hire:'Write 20 headline variants in 30 seconds.',
    duties:'Generate clickable, accurate headlines × multiple angles (curiosity, benefit, contrarian, list).',
    desc:'20 headlines per ask, across 5 angles (curiosity, benefit, contrarian, list, how-to). Pick the winner.',
    tags:['headline','copy'], demos:['Headlines for a blog post on async work'],
    price:0, uses:3220, rating:4.6, reviews:198 },
  { av:'🧷', slug:'microcopy-writer', nm:'Microcopy Writer', cat:'writing', sk:['writing','marketing'],
    hire:'Write the tiny words that make products feel polished.',
    duties:'Button labels, error messages, empty states, tooltips — all in voice.',
    desc:'Buttons, error messages, empty states, tooltips. The 5-word details that separate polish from amateur hour.',
    tags:['ux','microcopy'], demos:['Microcopy for a checkout flow'],
    price:1900, uses:380, rating:4.8, reviews:31 },
  { av:'🎬', slug:'script-writer', nm:'YouTube Script Writer', cat:'writing', sk:['writing','marketing','idea'],
    hire:'Write YouTube scripts that retain viewers past 30s.',
    duties:'Hook (5s) + tease + chapters + payoff + CTA. Built around retention curves.',
    desc:'Built around retention curves. Hook (5s) + tease + chapters + payoff + CTA, in your channel\'s voice.',
    tags:['youtube','script'], demos:['Write a script for "5 SaaS pricing mistakes"'],
    price:2400, uses:920, rating:4.8, reviews:62 },
  { av:'🪶', slug:'ghost-writer', nm:'Ghost Writer', cat:'writing', sk:['writing','idea'],
    hire:'Ghost-write LinkedIn posts in your voice.',
    duties:'Read 5 of your past posts to learn voice, then draft 5 new posts on the topics you give.',
    desc:'Studies 5 of your past posts to learn voice, then ghost-writes 5 new posts on your topics. Keeps showing up consistent.',
    tags:['linkedin','writing'], demos:['Ghost-write 5 LinkedIn posts on hiring senior engineers'],
    price:2900, uses:680, rating:4.8, reviews:54 },
  { av:'🧠', slug:'fiction-writer', nm:'Fiction Writer', cat:'writing', sk:['writing','idea'],
    hire:'Help draft fiction without losing your voice.',
    duties:'Plot help, scene drafting, dialogue polish, character consistency.',
    desc:'Plot help, scene drafting, dialogue polish, character consistency. Built to assist, not auto-generate.',
    tags:['fiction','creative'], demos:['Help me draft a tense kitchen scene'],
    price:1500, uses:840, rating:4.7, reviews:54 },
  { av:'📨', slug:'email-drafter', nm:'Email Drafter', cat:'writing', sk:['writing','support'],
    hire:'Reply to any email in 30 seconds.',
    duties:'Read incoming, suggest 3 replies (formal / friendly / direct), pick one to send.',
    desc:'Three reply options (formal / friendly / direct) for every email you stare at. Inbox zero, finally reachable.',
    tags:['email','productivity'], demos:['Reply to this client request'],
    price:0, uses:8920, rating:4.7, reviews:413, ribbon:'hot' },

  // ── OPS (8) ──
  { av:'✅', slug:'task-tracker', nm:'Task Tracker', cat:'ops', sk:['planning','support'],
    hire:'Sort messy todos into a focused day.',
    duties:'Sort by urgency × impact × effort. Output a top-5 day plan + everything else parked.',
    desc:'Throw a list of tasks at it; get back a top-5 day plan plus a parked list. No more "what should I do first" paralysis.',
    tags:['productivity','tasks'], demos:['Plan my day from this todo dump'],
    price:0, uses:5240, rating:4.8, reviews:286 },
  { av:'📋', slug:'meeting-notes', nm:'Meeting Note-Taker', cat:'ops', sk:['writing','analysis','planning'],
    hire:'Turn rambling meeting notes into structured action items.',
    duties:'Transcript or notes → structured summary → action items with owners and dates.',
    desc:'Drop a transcript or messy notes; get a clean summary plus action items with owners and dates.',
    tags:['meetings','productivity'], demos:['Process these meeting notes'],
    price:1500, uses:3140, rating:4.8, reviews:198, ribbon:'hot' },
  { av:'🗓️', slug:'calendar-optimizer', nm:'Calendar Optimizer', cat:'ops', sk:['planning','analysis'],
    hire:'Audit your calendar and reclaim deep work time.',
    duties:'Analyze the week, flag time-wasters, suggest a re-block with deep-work slots.',
    desc:'Audits last week, flags meetings that should\'ve been emails, suggests a re-block with deep-work slots. Run weekly.',
    tags:['calendar','productivity'], demos:['Audit my calendar from last week'],
    price:1900, uses:480, rating:4.7, reviews:38 },
  { av:'📥', slug:'inbox-zero', nm:'Inbox Zero AI', cat:'ops', sk:['support','writing','planning'],
    hire:'Triage your inbox in 5 minutes.',
    duties:'Sort into Reply / Archive / Schedule / Delegate. Draft the replies it can.',
    desc:'Sorts your inbox into 4 buckets (Reply / Archive / Schedule / Delegate) and drafts the replies it can. Done in 5.',
    tags:['email','productivity'], demos:['Triage today\'s 40 unread emails'],
    price:1900, uses:1840, rating:4.7, reviews:124 },
  { av:'💼', slug:'project-manager', nm:'Project Manager AI', cat:'ops', sk:['planning','analysis','support'],
    hire:'Run a project without being a PMP.',
    duties:'Break the goal into milestones, surface dependencies, surface risks early.',
    desc:'Break a goal into milestones, surface dependencies, flag risks early. Like a calm PM in your head.',
    tags:['pm','planning'], demos:['Plan the launch of an internal tool, deadline 6 weeks'],
    price:2400, uses:620, rating:4.8, reviews:48 },
  { av:'💸', slug:'expense-tracker', nm:'Expense Categorizer', cat:'ops', sk:['analysis','support'],
    hire:'Categorize expenses for tax season.',
    duties:'CSV in → categorized + flagged + ready for accountant.',
    desc:'CSV of card transactions in; categorized + flagged + ready-for-accountant out. Saves 4 hours every quarter.',
    tags:['finance','tax'], demos:['Categorize this Q3 expense report'],
    price:1500, uses:340, rating:4.6, reviews:24 },
  { av:'🎯', slug:'okr-tracker', nm:'OKR Tracker', cat:'ops', sk:['planning','analysis'],
    hire:'Write OKRs that aren\'t empty.',
    duties:'Goal in → 1 Objective + 3 measurable Key Results + check-in cadence.',
    desc:'Turns a vague goal into 1 Objective + 3 measurable KRs + a check-in cadence. Zero corporate-speak.',
    tags:['okr','planning'], demos:['Write OKRs for a growing engineering team'],
    price:1900, uses:280, rating:4.7, reviews:18 },
  { av:'🧑‍💼', slug:'hiring-tracker', nm:'Hiring Coordinator', cat:'ops', sk:['planning','writing','support'],
    hire:'Run a clean hiring loop without the chaos.',
    duties:'Track candidates, draft scheduling emails, summarize panel feedback into a recommendation.',
    desc:'Tracks candidates, drafts scheduling emails, summarizes panel feedback into a clean go/no-go recommendation.',
    tags:['hiring','hr'], demos:['Help me run an interview loop for a senior eng'],
    price:2400, uses:212, rating:4.8, reviews:18 },

  // ── OTHER (4) ──
  { av:'⚖️', slug:'contract-reviewer', nm:'Contract Reviewer', cat:'other', sk:['analysis','research'],
    hire:'Spot risky clauses before you sign.',
    duties:'Read the contract, flag clauses to push back on with a 1-line reason each.',
    desc:'Flags clauses you should push back on with a 1-line reason each. Not legal advice, but a great first pass.',
    tags:['legal','contract'], demos:['Review this SaaS MSA'],
    price:3900, uses:480, rating:4.8, reviews:38 },
  { av:'💹', slug:'financial-planner', nm:'Personal CFO', cat:'other', sk:['analysis','planning'],
    hire:'Plan your money like a calm advisor.',
    duties:'Income, savings, runway, big-decision sanity checks. Friendly, not preachy.',
    desc:'A calm advisor in your head. Income, savings, runway, big-decision sanity checks. Not financial advice — a thinking partner.',
    tags:['finance','personal'], demos:['Should I take this job offer at $180k vs my current $145k?'],
    price:2900, uses:380, rating:4.7, reviews:24 },
  { av:'🍳', slug:'recipe-creator', nm:'Recipe Creator', cat:'other', sk:['idea','writing'],
    hire:'Turn what\'s in your fridge into dinner.',
    duties:'Ingredients in → 3 recipe ideas with prep time + skill level.',
    desc:'List what\'s in your fridge; get 3 recipes with prep time and skill level. End the "what\'s for dinner" loop.',
    tags:['food','home'], demos:['Chicken, broccoli, garlic, lemon — make me dinner'],
    price:0, uses:1240, rating:4.6, reviews:72 },
  { av:'✈️', slug:'travel-planner', nm:'Travel Planner', cat:'other', sk:['planning','research'],
    hire:'Plan a trip that doesn\'t feel rushed.',
    duties:'Destination + days + vibe → day-by-day plan with food, walks, downtime.',
    desc:'Destination + days + vibe → a day-by-day plan with food, walks, downtime. Built to feel calm, not packed.',
    tags:['travel','planning'], demos:['Plan a 5-day Tokyo trip for two foodies'],
    price:1900, uses:920, rating:4.8, reviews:64 },
];

// ── Team specs (50) ──
//   Each team has 3-6 members. Member array specs use the same shorthand as
//   solo agents.
const SEED_TEAMS = [
  // ── E-commerce / launch teams ──
  { av:'🛍', slug:'team-ec-launch-pro', nm:'EC Launch Pro Team', cat:'other',
    goal:'Source winning products, render lifestyle photos, spin up Shopify, post on social, analyze sales.',
    desc:'Run an entire e-commerce business with 5 hand-tuned AI agents. Source → render → ship → post → analyze.',
    members:[
      { av:'🛍', nm:'Product Sourcer', sk:['research','analysis'], persona:'Hired for: Find products with margin > 50% and rising demand.\nDay-to-day: Scan Alibaba, Google Trends, Reddit; return top 3 candidates with margin × demand × differentiation scores.' },
      { av:'📸', nm:'Visual Designer', sk:['idea','marketing'], persona:'Hired for: Generate brand-consistent lifestyle photos.\nDay-to-day: 5 variants per product (golden hour / minimal / cozy / bold / studio) with intent for each shot.' },
      { av:'🌐', nm:'Storefront Architect', sk:['coding','planning'], persona:'Hired for: Spin up the Shopify store end-to-end.\nDay-to-day: Pages, payments, shipping zones, SEO, pre-launch checklist.' },
      { av:'📱', nm:'Social Manager', sk:['marketing','sns','writing'], persona:'Hired for: Cross-post the launch to X / IG / TikTok at peak times.\nDay-to-day: Hashtag optimization, post text, best-time scheduling, image alignment.' },
      { av:'📊', nm:'Revenue Analyst', sk:['analysis','planning'], persona:'Hired for: Monitor sales and surface improvement bets.\nDay-to-day: Stripe webhook → daily summary → product-level analysis → action items.' },
    ],
    tags:['ecommerce','shopify'], demos:['Launch a pet products store from scratch'],
    price:9800, uses:410, rating:4.9, reviews:132, ribbon:'hot' },

  { av:'📱', slug:'team-sns-growth', nm:'SNS Growth Squad', cat:'marketing',
    goal:'Spot trends → write posts → schedule across X / Instagram / TikTok at peak engagement times.',
    desc:'Trend mining + content writing + scheduling — a 3-agent team for organic SNS growth.',
    members:[
      { av:'📈', nm:'Trend Spotter', sk:['research','sns'], persona:'Hired for: Surface 5 daily trends in our niche.\nDay-to-day: Mine signals → relevance score → post candidates.' },
      { av:'✍️', nm:'Content Writer', sk:['writing','marketing'], persona:'Hired for: Write tweets/captions that hit.\nDay-to-day: Hook → body → CTA, emoji + line breaks tuned per platform.' },
      { av:'📅', nm:'Scheduler', sk:['planning','sns'], persona:'Hired for: Schedule at peak times on each platform.\nDay-to-day: Best-time table → multiple posts/day → next-day learning loop.' },
    ],
    tags:['sns','marketing'], demos:['Plan a week of social content for a SaaS founder'],
    price:0, uses:5120, rating:4.8, reviews:284, ribbon:'hot' },

  { av:'💼', slug:'team-solo-founder', nm:'Solo Founder Toolkit', cat:'ops',
    goal:'Email writer + meeting note-taker + task tracker. Daily essentials for solo founders.',
    desc:'The daily essentials. Reply to email, structure meeting notes, plan today — all without context switching.',
    members:[
      { av:'📧', nm:'Email Drafter', sk:['writing','support'], persona:'Hired for: 30-second reply emails.\nDay-to-day: Three options (formal / friendly / direct) for every incoming email.' },
      { av:'📝', nm:'Note Taker', sk:['writing','analysis'], persona:'Hired for: Convert messy notes into structured todos.\nDay-to-day: Recording/notes → minutes → action items with deadlines.' },
      { av:'✅', nm:'Task Tracker', sk:['planning','support'], persona:'Hired for: Prioritize a chaotic todo list.\nDay-to-day: Sort by deadline × impact × effort; surface today\'s top 5.' },
    ],
    tags:['productivity','founder'], demos:['Plan my Monday + reply to overnight emails'],
    price:0, uses:8240, rating:4.8, reviews:412, ribbon:'hot' },

  { av:'🎓', slug:'team-tutor-squad', nm:'Personal Tutor Squad', cat:'other',
    goal:'Researcher + explainer + quiz maker. Learn anything new — coding, finance, language — with a 3-agent crew.',
    desc:'Research + explain + quiz, around any topic. Built for self-directed learners who want to actually retain the material.',
    members:[
      { av:'🔍', nm:'Researcher', sk:['research'], persona:'Hired for: Pull 3 best sources on a topic.\nDay-to-day: Web + academic search; summary + citations.' },
      { av:'🎓', nm:'Explainer', sk:['teaching','writing'], persona:'Hired for: Explain so a 12-year-old gets it.\nDay-to-day: Core concept → analogy → diagram-as-text, 200-400 words.' },
      { av:'🧠', nm:'Quiz Maker', sk:['teaching','analysis'], persona:'Hired for: Build a 5-question retention quiz.\nDay-to-day: 3 multiple-choice + 2 short-answer with explanations.' },
    ],
    tags:['education','learning'], demos:['Help me learn Rust ownership'],
    price:0, uses:3240, rating:4.9, reviews:218 },

  { av:'💻', slug:'team-dev-squad', nm:'Dev Squad', cat:'other',
    goal:'Code reviewer + bug fixer + test writer + deploy helper. Boost code quality without team meetings.',
    desc:'Reviewer + bug fixer + test writer + deploy helper. Ship better code without the meeting chains.',
    members:[
      { av:'🔍', nm:'Code Reviewer', sk:['coding','analysis'], persona:'Hired for: Review PRs for bugs, security, readability.\nDay-to-day: Diff in → line-level comments → suggested fixes → severity labels.' },
      { av:'🔧', nm:'Bug Fixer', sk:['coding'], persona:'Hired for: Convert stack traces to fix code.\nDay-to-day: Reproduce → root cause → minimal patch → regression test.' },
      { av:'🧪', nm:'Test Writer', sk:['coding','analysis'], persona:'Hired for: Write the right tests.\nDay-to-day: Unit → integration → e2e priority + edge cases + CI-ready.' },
      { av:'🚀', nm:'Deploy Helper', sk:['coding','planning'], persona:'Hired for: Deploy without surprises.\nDay-to-day: Pre-deploy checklist → rollout plan → rollback plan → smoke tests.' },
    ],
    tags:['engineering','dev'], demos:['Review a PR adding payment retry logic'],
    price:3900, uses:1820, rating:4.9, reviews:108, ribbon:'hot' },

  // ── Marketing teams (a sampler — 9 more) ──
  { av:'🚀', slug:'team-brand-launch', nm:'Brand Launch Studio', cat:'marketing',
    goal:'Brand voice + landing copy + launch posts + PR pitches. Ship a launch in a week.',
    desc:'Voice + landing + launch posts + PR. From "we exist" to a polished launch in 7 days.',
    members:[
      { av:'🏷️', nm:'Brand Strategist', sk:['planning','marketing'], persona:'Hired for: Define voice + positioning.\nDay-to-day: Tone-of-voice doc, audience archetypes, messaging matrix.' },
      { av:'🎨', nm:'Landing Page Writer', sk:['writing','marketing'], persona:'Hired for: Write the homepage.\nDay-to-day: Hero, benefits, social proof, objections, CTA — conversion-tuned.' },
      { av:'📱', nm:'Launch Day Poster', sk:['writing','sns'], persona:'Hired for: Coordinate launch-day posts.\nDay-to-day: Tweets, IG captions, LinkedIn, hooks per platform.' },
      { av:'📰', nm:'PR Pitcher', sk:['writing','research'], persona:'Hired for: Pitch the right journalists.\nDay-to-day: Find 10 relevant beats, personalized pitch each, 1 follow-up.' },
    ],
    tags:['brand','launch','marketing'], demos:['Launch a sustainable activewear brand next week'],
    price:7400, uses:212, rating:4.9, reviews:18, ribbon:'new' },

  { av:'📰', slug:'team-content-mill', nm:'Content Mill Crew', cat:'marketing',
    goal:'Topic research + outline + draft + edit + repurpose into 5 channels.',
    desc:'Research → outline → draft → edit → repurpose. One topic in, ready content for blog + social + email out.',
    members:[
      { av:'🔍', nm:'Topic Researcher', sk:['research','analysis'], persona:'Hired for: Find topics with traffic potential.\nDay-to-day: Keyword + SERP + audience-fit scoring.' },
      { av:'📝', nm:'Outliner', sk:['writing','planning'], persona:'Hired for: Outline pieces that flow.\nDay-to-day: H1/H2/H3 structure + key points per section.' },
      { av:'✍️', nm:'Draft Writer', sk:['writing'], persona:'Hired for: Write the long-form draft.\nDay-to-day: 1500 words + internal links + images-as-text suggestions.' },
      { av:'✏️', nm:'Editor', sk:['writing','analysis'], persona:'Hired for: Tighten and sharpen.\nDay-to-day: Remove fluff, fix voice, suggest restructures.' },
      { av:'🔁', nm:'Repurposer', sk:['writing','marketing'], persona:'Hired for: Slice content into 5 channels.\nDay-to-day: Twitter thread, LinkedIn post, IG carousel script, email, podcast notes.' },
    ],
    tags:['content','marketing'], demos:['Build a content engine for a B2B SaaS'],
    price:5900, uses:480, rating:4.8, reviews:34 },

  { av:'🔎', slug:'team-seo-squad', nm:'SEO Squad', cat:'marketing',
    goal:'Keyword research + SERP analysis + writing + on-page + internal linking + tracking.',
    desc:'A pod that owns SEO end-to-end. Research, write, optimize, track — repeat weekly.',
    members:[
      { av:'🗝️', nm:'Keyword Researcher', sk:['research','analysis'], persona:'Hired for: Find winnable keywords.\nDay-to-day: Volume × intent × difficulty; cluster into pillars.' },
      { av:'✍️', nm:'SEO Writer', sk:['writing','research'], persona:'Hired for: Write posts that rank.\nDay-to-day: Outline → 1500-word draft → internal links → meta.' },
      { av:'🔗', nm:'Link Architect', sk:['planning','analysis'], persona:'Hired for: Build internal link structure.\nDay-to-day: Topic clusters, link maps, anchor variety.' },
    ],
    tags:['seo','marketing'], demos:['Build an SEO plan for a personal-finance blog'],
    price:4900, uses:620, rating:4.8, reviews:48 },

  { av:'🎯', slug:'team-ad-studio', nm:'Ad Studio Crew', cat:'marketing',
    goal:'Audience research + ad copy variants + landing page match + creative brief.',
    desc:'Research + write + match + brief. A pod for paid acquisition that ships A/B-ready ad sets.',
    members:[
      { av:'🎯', nm:'Ad Copy Writer', sk:['writing','marketing'], persona:'Hired for: 10 ad variants per ask.\nDay-to-day: Hook + body + CTA × 5 angles × 2 lengths.' },
      { av:'🧑‍🤝‍🧑', nm:'Audience Persona', sk:['research','analysis'], persona:'Hired for: Define who the ad is for.\nDay-to-day: 3 personas with goals, frustrations, jobs-to-be-done.' },
      { av:'🎨', nm:'Creative Briefer', sk:['idea','writing'], persona:'Hired for: Brief designers/video.\nDay-to-day: Concept × 3 visual directions + script-as-text.' },
    ],
    tags:['ads','marketing'], demos:['Plan a launch ad campaign for a meal kit'],
    price:3900, uses:382, rating:4.7, reviews:32 },

  { av:'💌', slug:'team-newsletter', nm:'Newsletter Crew', cat:'marketing',
    goal:'Curate the week + write intro + write sections + write subject line + newsletter design notes.',
    desc:'A weekly newsletter pod. Curate, write, polish, ship.',
    members:[
      { av:'🔍', nm:'Curator', sk:['research'], persona:'Hired for: Find the week\'s 5 best stories.\nDay-to-day: Scan signals + relevance scoring + summary blurbs.' },
      { av:'💌', nm:'Writer', sk:['writing'], persona:'Hired for: Write punchy sections.\nDay-to-day: Intro + 3 main + outro, in voice.' },
      { av:'🪄', nm:'Subject Line Pro', sk:['writing','marketing'], persona:'Hired for: Write subjects that get opened.\nDay-to-day: 5 options per issue + open-rate hypothesis each.' },
    ],
    tags:['newsletter','email'], demos:['Write this week\'s issue on AI productivity'],
    price:1900, uses:680, rating:4.8, reviews:42 },

  { av:'📰', slug:'team-pr-crew', nm:'PR Crew', cat:'marketing',
    goal:'Find journalists + research them + pitch + follow up + measure coverage.',
    desc:'Find + research + pitch + follow + measure. PR for founders who don\'t want an agency.',
    members:[
      { av:'🔎', nm:'Journalist Finder', sk:['research'], persona:'Hired for: Build the right press list.\nDay-to-day: Beat search + recent coverage + reachability.' },
      { av:'✍️', nm:'Pitch Writer', sk:['writing','marketing'], persona:'Hired for: Personalized pitches.\nDay-to-day: Each pitch references a recent piece by that journalist.' },
      { av:'📈', nm:'Coverage Tracker', sk:['analysis','research'], persona:'Hired for: Track who covered.\nDay-to-day: Mentions, audience reach, lessons for next pitch.' },
    ],
    tags:['pr','press'], demos:['Run a press push for a fintech launch'],
    price:5900, uses:148, rating:4.8, reviews:14 },

  { av:'🤝', slug:'team-influencer', nm:'Influencer Outreach Squad', cat:'marketing',
    goal:'Find creators + draft outreach + manage handoff + track results.',
    desc:'Build a creator program from scratch. Find, pitch, brief, track — without an agency.',
    members:[
      { av:'🔎', nm:'Creator Finder', sk:['research','sns'], persona:'Hired for: Find aligned creators.\nDay-to-day: Niche + reach + engagement-rate filtering.' },
      { av:'✍️', nm:'Outreach Writer', sk:['writing','marketing'], persona:'Hired for: Personalized DMs.\nDay-to-day: Reference recent post + clear value + soft ask.' },
      { av:'📋', nm:'Brief Builder', sk:['planning','writing'], persona:'Hired for: Brief creators clearly.\nDay-to-day: Goals + do/don\'t + sample hooks + tracking link.' },
    ],
    tags:['influencer','marketing'], demos:['Find 20 IG creators in the home-coffee niche'],
    price:4900, uses:240, rating:4.7, reviews:18 },

  { av:'📲', slug:'team-aso', nm:'App Store Optimization Crew', cat:'marketing',
    goal:'Keyword research + screenshots + descriptions + reviews + competitor analysis.',
    desc:'Keyword research + listing copy + screenshot ideas + competitor analysis. ASO without paying $5k/mo.',
    members:[
      { av:'🔎', nm:'ASO Keyword Researcher', sk:['research','analysis'], persona:'Hired for: Find keywords your app should rank for.\nDay-to-day: Volume + difficulty + competitor matrix.' },
      { av:'✍️', nm:'Listing Copywriter', sk:['writing','marketing'], persona:'Hired for: Write title + subtitle + description.\nDay-to-day: Char-limit-aware, keyword-optimized, conversion-focused.' },
      { av:'🖼️', nm:'Screenshot Writer', sk:['writing','idea'], persona:'Hired for: Draft screenshot text overlays.\nDay-to-day: 5 frames with hook + benefit + minimum-words wording.' },
    ],
    tags:['aso','mobile'], demos:['ASO plan for a habit tracker iOS app'],
    price:3900, uses:120, rating:4.8, reviews:9 },

  { av:'📧', slug:'team-email-mkt', nm:'Email Marketing Pod', cat:'marketing',
    goal:'List health + segmentation + welcome series + drip campaigns + win-back.',
    desc:'Welcome series + drips + win-back + list health. Email that ships and converts.',
    members:[
      { av:'📧', nm:'Series Writer', sk:['writing','marketing'], persona:'Hired for: Write welcome series.\nDay-to-day: 5 emails over 14 days, each with single CTA.' },
      { av:'🎯', nm:'Segment Strategist', sk:['analysis','planning'], persona:'Hired for: Build smart segments.\nDay-to-day: RFM analysis + behavior triggers + relevant content.' },
      { av:'🪄', nm:'Subject Line Pro', sk:['writing','marketing'], persona:'Hired for: Drive open rates.\nDay-to-day: 5 options + win-back-specific lines.' },
    ],
    tags:['email','marketing'], demos:['Build a welcome series for a SaaS'],
    price:3900, uses:512, rating:4.7, reviews:42 },

  { av:'🐦', slug:'team-twitter-pod', nm:'Twitter Growth Pod', cat:'marketing',
    goal:'Account positioning + content calendar + thread writing + engagement playbook.',
    desc:'Position + plan + write + engage. A pod for founders building in public on X.',
    members:[
      { av:'🎯', nm:'Account Strategist', sk:['marketing','planning'], persona:'Hired for: Position your X account.\nDay-to-day: Audience + niche + 3 content pillars.' },
      { av:'🧵', nm:'Thread Writer', sk:['writing','marketing'], persona:'Hired for: Write threads.\nDay-to-day: Hook tweet + 7-9 body + CTA, dialed for retention.' },
      { av:'💬', nm:'Engagement Playbook', sk:['marketing','sns'], persona:'Hired for: Build an engagement routine.\nDay-to-day: Reply prompts + which accounts to engage + cadence.' },
    ],
    tags:['twitter','sns'], demos:['Position my X account as a startup founder'],
    price:2900, uses:880, rating:4.8, reviews:64 },

  // ── Sales teams (4 more) ──
  { av:'📩', slug:'team-outbound-sales', nm:'Outbound Crew', cat:'sales',
    goal:'Build target list → research each → 3-step sequence → handle replies.',
    desc:'A 4-agent outbound pod that ships a personalized cadence per lead.',
    members:[
      { av:'🎯', nm:'Targeter', sk:['research','analysis'], persona:'Hired for: Build the right target list.\nDay-to-day: ICP score + LinkedIn signals + cohorting.' },
      { av:'🔍', nm:'Researcher', sk:['research','writing'], persona:'Hired for: Find the personalization angle.\nDay-to-day: Recent activity + company news + relevant trigger.' },
      { av:'✍️', nm:'Sequence Writer', sk:['writing','marketing'], persona:'Hired for: Write the 3-step cadence.\nDay-to-day: Opener + 2 follow-ups, no fake personalization.' },
      { av:'💬', nm:'Reply Handler', sk:['writing','support'], persona:'Hired for: Reply to inbound responses.\nDay-to-day: Tone-match + qualifying questions + next-step booking.' },
    ],
    tags:['sales','outbound'], demos:['Build an outbound campaign for a Series A SaaS'],
    price:5900, uses:480, rating:4.8, reviews:38, ribbon:'hot' },

  { av:'🎬', slug:'team-demo-squad', nm:'Demo Squad', cat:'sales',
    goal:'Pre-call research + demo script + objection handling + post-call summary.',
    desc:'4-agent demo team: research, script, objection handling, post-call summary. Higher win rate, less prep.',
    members:[
      { av:'🔍', nm:'Pre-call Researcher', sk:['research'], persona:'Hired for: Read the prospect.\nDay-to-day: Public stack + recent activity + likely use case.' },
      { av:'🎬', nm:'Demo Scripter', sk:['writing','planning'], persona:'Hired for: Tailor the demo script.\nDay-to-day: Pain → product → value, with personalized hooks.' },
      { av:'🛡️', nm:'Objection Coach', sk:['support','analysis'], persona:'Hired for: Predict objections.\nDay-to-day: Top 5 likely objections + matching responses.' },
      { av:'📋', nm:'Post-call Summarizer', sk:['writing','analysis'], persona:'Hired for: Summarize the call.\nDay-to-day: Highlights + action items + next steps to send.' },
    ],
    tags:['sales','demo'], demos:['Prep a demo for a finance team at a 300-person company'],
    price:4900, uses:240, rating:4.9, reviews:21 },

  { av:'📞', slug:'team-inside-sales', nm:'Inside Sales Pod', cat:'sales',
    goal:'Inbound triage + qualification + scheduling + handoff brief.',
    desc:'Triage + qualify + schedule + brief. Cleaner handoffs from MQL to AE.',
    members:[
      { av:'📥', nm:'Inbound Triager', sk:['support','analysis'], persona:'Hired for: Triage inbound leads.\nDay-to-day: Score + route + auto-reply.' },
      { av:'🎯', nm:'Qualifier', sk:['analysis','support'], persona:'Hired for: Qualify in 60 seconds.\nDay-to-day: 3 disqualifying questions + ICP fit.' },
      { av:'📅', nm:'Scheduler', sk:['planning','support'], persona:'Hired for: Book the call.\nDay-to-day: Tone-match + calendar links + reminder cadence.' },
    ],
    tags:['sales','inside'], demos:['Process this week\'s 40 inbound leads'],
    price:3900, uses:312, rating:4.7, reviews:24 },

  { av:'💼', slug:'team-account-mgmt', nm:'Account Management Pod', cat:'sales',
    goal:'QBR prep + renewal forecast + churn-risk flagging + expansion ideas.',
    desc:'QBR prep + renewal forecast + churn risk + expansion. A pod for CSM/AM teams.',
    members:[
      { av:'📊', nm:'QBR Prepper', sk:['analysis','planning','writing'], persona:'Hired for: Prep quarterly business reviews.\nDay-to-day: Usage + value delivered + roadmap fit + asks.' },
      { av:'🚨', nm:'Churn Spotter', sk:['analysis','research'], persona:'Hired for: Flag accounts at risk.\nDay-to-day: Usage drop + sentiment + product fit signals.' },
      { av:'💎', nm:'Expansion Ideator', sk:['idea','planning'], persona:'Hired for: Spot expansion paths.\nDay-to-day: Adjacent use cases + budget signals + framing.' },
    ],
    tags:['sales','csm'], demos:['Prep QBR for our top 3 accounts'],
    price:4900, uses:148, rating:4.8, reviews:12 },

  // ── CS teams (5) ──
  { av:'🤝', slug:'team-cs-tier1', nm:'CS Tier 1 Pod', cat:'ops',
    goal:'Triage tickets + first reply + escalation routing + KB build-up.',
    desc:'Triage + first reply + escalation + KB. A pod that handles 70% of inbound without humans.',
    members:[
      { av:'📥', nm:'Triager', sk:['support','analysis'], persona:'Hired for: Sort and tag tickets.\nDay-to-day: Category + priority + suggested owner.' },
      { av:'💬', nm:'First Responder', sk:['writing','support'], persona:'Hired for: Reply with empathy and clarity.\nDay-to-day: Confirm + clarify + initial answer; escalate if blocked.' },
      { av:'📚', nm:'KB Builder', sk:['writing','planning'], persona:'Hired for: Build the KB from solved tickets.\nDay-to-day: Pattern → article → tag, weekly.' },
    ],
    tags:['support','ops'], demos:['Process today\'s 50 tickets'],
    price:0, uses:1820, rating:4.7, reviews:122 },

  { av:'🌍', slug:'team-multilingual-cs', nm:'Multilingual Support Crew', cat:'ops',
    goal:'JA/EN/ES/FR/DE support across email + chat with consistent voice.',
    desc:'Same brand voice across 5 languages. Triage, reply, escalate — without 5x the headcount.',
    members:[
      { av:'🇯🇵', nm:'JA Support', sk:['translate','support','writing'], persona:'Hired for: 日本語のサポート対応。\nDay-to-day: お客様の課題確認 → 解決手順 → エスカレーション判定。' },
      { av:'🇪🇸', nm:'ES Support', sk:['translate','support','writing'], persona:'Hired for: Soporte en español.\nDay-to-day: Confirmar pregunta → respuesta → escalado si bloqueado.' },
      { av:'🌐', nm:'Voice Keeper', sk:['writing','analysis'], persona:'Hired for: Keep brand voice consistent across languages.\nDay-to-day: Tone audit + voice glossary updates.' },
    ],
    tags:['support','i18n'], demos:['Reply to this Japanese support ticket'],
    price:5900, uses:212, rating:4.8, reviews:18 },

  { av:'🎓', slug:'team-onboarding', nm:'Onboarding Crew', cat:'ops',
    goal:'Welcome → milestone tracking → check-ins → graduation.',
    desc:'Drive first-value time down. Welcome, track milestones, check in, graduate the user to power-mode.',
    members:[
      { av:'👋', nm:'Welcomer', sk:['writing','support'], persona:'Hired for: Send the warmest welcome.\nDay-to-day: Personalized welcome + first task + clear next step.' },
      { av:'📊', nm:'Milestone Tracker', sk:['analysis','planning'], persona:'Hired for: Track activation milestones.\nDay-to-day: Did they finish step 1? 2? 3? Surface stuck users.' },
      { av:'💬', nm:'Check-in Specialist', sk:['support','writing'], persona:'Hired for: Reach out at the right moments.\nDay-to-day: Day 1, 7, 14 nudges with relevant content.' },
    ],
    tags:['onboarding','cs'], demos:['Build a 14-day onboarding flow'],
    price:3900, uses:212, rating:4.7, reviews:18 },

  { av:'🛟', slug:'team-retention', nm:'Retention Squad', cat:'ops',
    goal:'Detect churn signals → personalized save plays → win-back if churned.',
    desc:'Detect signals + run save plays + win back. Lower churn, higher LTV.',
    members:[
      { av:'🚨', nm:'Churn Detector', sk:['analysis','research'], persona:'Hired for: Spot churn before it happens.\nDay-to-day: Usage + sentiment + product fit signals.' },
      { av:'❤️', nm:'Save Specialist', sk:['support','writing'], persona:'Hired for: Run save plays.\nDay-to-day: Personalized outreach + offer + listening.' },
      { av:'🔁', nm:'Win-back Writer', sk:['writing','marketing'], persona:'Hired for: Win back churned users.\nDay-to-day: Email series with new value + soft re-engage.' },
    ],
    tags:['retention','cs'], demos:['Build a save play for at-risk accounts'],
    price:4900, uses:148, rating:4.8, reviews:12 },

  { av:'💸', slug:'team-refund-crew', nm:'Refund + Dispute Crew', cat:'ops',
    goal:'Process refund requests + dispute Stripe chargebacks + write decisions.',
    desc:'Process requests + dispute chargebacks + write decisions. Stop losing arbitrary disputes.',
    members:[
      { av:'📋', nm:'Refund Processor', sk:['support','analysis'], persona:'Hired for: Process refund requests.\nDay-to-day: Verify + calculate + draft response.' },
      { av:'⚖️', nm:'Dispute Writer', sk:['writing','analysis'], persona:'Hired for: Win Stripe chargebacks.\nDay-to-day: Compelling evidence + clear timeline + concise narrative.' },
    ],
    tags:['support','finance'], demos:['Process this refund request and write a response'],
    price:1900, uses:240, rating:4.7, reviews:18 },

  // ── Engineering teams (7) ──
  { av:'🧪', slug:'team-qa-pod', nm:'QA Pod', cat:'other',
    goal:'Test plan + unit tests + e2e suite + regression triage.',
    desc:'Test plan + unit tests + e2e + regression. Confidence before every deploy.',
    members:[
      { av:'📋', nm:'Test Planner', sk:['planning','coding'], persona:'Hired for: Plan what to test.\nDay-to-day: Risk-based prioritization + coverage map.' },
      { av:'🧪', nm:'Unit Test Writer', sk:['coding','analysis'], persona:'Hired for: Write the right tests.\nDay-to-day: Edge cases + happy path + failure modes.' },
      { av:'🌐', nm:'E2E Test Writer', sk:['coding','planning'], persona:'Hired for: Cover real user flows.\nDay-to-day: Critical paths + auth + state + side effects.' },
      { av:'🚨', nm:'Regression Triager', sk:['analysis','coding'], persona:'Hired for: Triage failed tests.\nDay-to-day: Flaky vs. real + bisect + root cause.' },
    ],
    tags:['qa','engineering'], demos:['Build a QA plan for a checkout feature'],
    price:5900, uses:312, rating:4.9, reviews:28 },

  { av:'⚙️', slug:'team-devops-crew', nm:'DevOps Crew', cat:'other',
    goal:'CI/CD setup + monitoring + alerting + on-call playbooks.',
    desc:'CI/CD + monitoring + alerting + on-call. The infra pod every team needs.',
    members:[
      { av:'🚀', nm:'CI/CD Builder', sk:['coding','planning'], persona:'Hired for: Build pipelines.\nDay-to-day: Build → test → deploy + rollback + secrets.' },
      { av:'📡', nm:'Monitor', sk:['analysis','coding'], persona:'Hired for: Build observability.\nDay-to-day: Logs + metrics + traces + dashboards.' },
      { av:'🔔', nm:'Alert Tuner', sk:['analysis','planning'], persona:'Hired for: Make alerts useful.\nDay-to-day: SLO-based + actionable + paginated.' },
      { av:'📖', nm:'Runbook Writer', sk:['writing','coding'], persona:'Hired for: Write on-call runbooks.\nDay-to-day: Symptom → triage → fix or escalate.' },
    ],
    tags:['devops','infra'], demos:['Set up CI/CD for a Node.js service'],
    price:6900, uses:212, rating:4.9, reviews:18 },

  { av:'🛡️', slug:'team-security-audit', nm:'Security Audit Crew', cat:'other',
    goal:'Threat model + dependency audit + security review + remediation plan.',
    desc:'Threat model + audit + review + remediate. Pre-launch security pass without hiring a firm.',
    members:[
      { av:'🎯', nm:'Threat Modeler', sk:['analysis','planning'], persona:'Hired for: Model attack surface.\nDay-to-day: Trust boundaries + assets + threats + mitigations.' },
      { av:'📦', nm:'Dependency Auditor', sk:['coding','analysis'], persona:'Hired for: Scan dependencies.\nDay-to-day: CVE check + license + freshness + alternatives.' },
      { av:'🔍', nm:'Code Reviewer (Security)', sk:['coding','analysis'], persona:'Hired for: Spot security bugs in code.\nDay-to-day: Auth, input validation, secrets, IDOR.' },
    ],
    tags:['security','engineering'], demos:['Audit a Node.js auth service'],
    price:7900, uses:96, rating:4.9, reviews:8 },

  { av:'🌐', slug:'team-api-builder', nm:'API Builder Crew', cat:'other',
    goal:'API design + implementation + docs + test client.',
    desc:'Design + implement + docs + test client. Ship a clean API the first time.',
    members:[
      { av:'📐', nm:'API Designer', sk:['planning','coding'], persona:'Hired for: Design the right API.\nDay-to-day: REST or RPC, resources, errors, versioning.' },
      { av:'💻', nm:'Implementer', sk:['coding'], persona:'Hired for: Build the API.\nDay-to-day: Routes, validation, auth, error mapping.' },
      { av:'📚', nm:'Doc Writer', sk:['writing','coding'], persona:'Hired for: Write the docs.\nDay-to-day: Quickstart + ref + examples that copy-paste run.' },
    ],
    tags:['api','engineering'], demos:['Design a billing API'],
    price:5900, uses:240, rating:4.9, reviews:21 },

  { av:'📱', slug:'team-mobile-app', nm:'Mobile App Crew', cat:'other',
    goal:'iOS/Android scaffolding + auth + core flows + ASO.',
    desc:'Scaffold + auth + core flows + ASO. From idea to App Store submission.',
    members:[
      { av:'📱', nm:'Mobile Architect', sk:['coding','planning'], persona:'Hired for: Scaffold a mobile app.\nDay-to-day: Stack pick, navigation, state, networking.' },
      { av:'🔐', nm:'Auth Builder', sk:['coding'], persona:'Hired for: Build sign-in flows.\nDay-to-day: Email + social + biometric + sessions.' },
      { av:'🖼️', nm:'UX Implementer', sk:['coding','idea'], persona:'Hired for: Implement core flows.\nDay-to-day: List, detail, action, feedback states.' },
    ],
    tags:['mobile','engineering'], demos:['Scaffold a habit tracker iOS app'],
    price:5900, uses:148, rating:4.8, reviews:12 },

  { av:'🤖', slug:'team-ml-trio', nm:'ML Engineering Trio', cat:'other',
    goal:'Data prep + model training + serving + monitoring.',
    desc:'Data → train → serve → monitor. Ship ML features without an ML team.',
    members:[
      { av:'🧮', nm:'Data Engineer', sk:['coding','analysis'], persona:'Hired for: Build the data pipeline.\nDay-to-day: ETL, validation, feature engineering.' },
      { av:'🎯', nm:'Model Trainer', sk:['coding','research'], persona:'Hired for: Train models.\nDay-to-day: Baseline + iterate + evaluate + deploy.' },
      { av:'📡', nm:'Serving + Monitoring', sk:['coding','analysis'], persona:'Hired for: Serve and monitor.\nDay-to-day: Latency, drift, accuracy, fallbacks.' },
    ],
    tags:['ml','engineering'], demos:['Build a personalization model for an e-commerce site'],
    price:7900, uses:96, rating:4.9, reviews:8 },

  { av:'📚', slug:'team-tech-doc', nm:'Tech Doc Crew', cat:'other',
    goal:'README + Quickstart + API ref + tutorials + migration guides.',
    desc:'Comprehensive dev docs. README + Quickstart + ref + tutorials + migration. Examples-first.',
    members:[
      { av:'📖', nm:'Quickstart Writer', sk:['writing','coding'], persona:'Hired for: Write the 5-minute path.\nDay-to-day: Install → first request → first result, copy-paste only.' },
      { av:'📚', nm:'Reference Writer', sk:['writing','coding'], persona:'Hired for: Write API reference.\nDay-to-day: Per endpoint + params + responses + examples.' },
      { av:'🎓', nm:'Tutorial Writer', sk:['writing','coding','teaching'], persona:'Hired for: Write end-to-end tutorials.\nDay-to-day: Goal → steps → verify → next.' },
    ],
    tags:['docs','engineering'], demos:['Write the README for a payments SDK'],
    price:4900, uses:312, rating:4.9, reviews:24 },

  // ── Education teams (3) ──
  { av:'🎓', slug:'team-course-creator', nm:'Course Creator Crew', cat:'other',
    goal:'Curriculum design + lesson plans + slide content + quizzes + assignments.',
    desc:'Curriculum + lessons + slides + quizzes + assignments. Build a course in a week.',
    members:[
      { av:'📐', nm:'Curriculum Designer', sk:['planning','teaching'], persona:'Hired for: Design the arc.\nDay-to-day: Modules + objectives + learning ladder.' },
      { av:'📝', nm:'Lesson Writer', sk:['writing','teaching'], persona:'Hired for: Write lessons.\nDay-to-day: Hook + core idea + examples + check-for-understanding.' },
      { av:'🖼️', nm:'Slide Maker', sk:['writing','idea'], persona:'Hired for: Outline slide content.\nDay-to-day: One idea per slide + visual cue + speaker notes.' },
      { av:'🧠', nm:'Assessment Builder', sk:['teaching','analysis'], persona:'Hired for: Build quizzes + assignments.\nDay-to-day: Recall + apply + transfer questions.' },
    ],
    tags:['course','education'], demos:['Build a 6-week course on product management'],
    price:5900, uses:148, rating:4.9, reviews:12 },

  { av:'🧒', slug:'team-kids-tutor', nm:'Kids Tutor Squad', cat:'other',
    goal:'Math + reading + fun-fact spark + parent updates.',
    desc:'Math + reading + curiosity sparks + parent updates. A patient pod for elementary-age kids.',
    members:[
      { av:'➗', nm:'Math Tutor', sk:['teaching','analysis'], persona:'Hired for: Teach math patiently.\nDay-to-day: Story-based problems + step-by-step + cheering.' },
      { av:'📖', nm:'Reading Tutor', sk:['teaching','writing'], persona:'Hired for: Build reading skills.\nDay-to-day: Phonics + fluency + comprehension Q&A.' },
      { av:'🌟', nm:'Curiosity Sparker', sk:['teaching','idea'], persona:'Hired for: Surprise the kid daily.\nDay-to-day: 1 wow-fact + 1 hands-on tiny experiment.' },
    ],
    tags:['kids','education'], demos:['Teach long division to a 4th grader'],
    price:1900, uses:480, rating:4.9, reviews:42 },

  { av:'💼', slug:'team-career-coach', nm:'Career Coaching Crew', cat:'other',
    goal:'Resume + cover letter + interview prep + negotiation playbook.',
    desc:'Resume + cover letter + interview prep + negotiation. Job-search end-to-end.',
    members:[
      { av:'📄', nm:'Resume Writer', sk:['writing','analysis'], persona:'Hired for: Write outcome-focused resumes.\nDay-to-day: STAR-format bullets, quantified, ATS-friendly.' },
      { av:'💌', nm:'Cover Letter Pro', sk:['writing','marketing'], persona:'Hired for: Write personal cover letters.\nDay-to-day: Hook + match + close, ≤300 words.' },
      { av:'🎤', nm:'Interview Coach', sk:['teaching','planning'], persona:'Hired for: Mock interview.\nDay-to-day: Behavioral, technical, system design — feedback included.' },
      { av:'💸', nm:'Negotiator', sk:['planning','writing'], persona:'Hired for: Negotiate the offer.\nDay-to-day: Anchors + counter + email drafts.' },
    ],
    tags:['career','coaching'], demos:['Help me apply for a senior PM role'],
    price:4900, uses:480, rating:4.9, reviews:38 },

  // ── Productivity teams (5 more) ──
  { av:'🦄', slug:'team-indie-hacker', nm:'Indie Hacker Toolkit', cat:'ops',
    goal:'Idea validation + MVP planning + landing page + launch posts + analytics.',
    desc:'Validate + plan + build + launch + measure. The full indie loop in one team.',
    members:[
      { av:'💡', nm:'Idea Validator', sk:['research','analysis','idea'], persona:'Hired for: Pressure-test ideas.\nDay-to-day: Demand signals + competitor + uniqueness + would-pay.' },
      { av:'🗓️', nm:'MVP Planner', sk:['planning','coding'], persona:'Hired for: Plan the smallest valuable thing.\nDay-to-day: 1-week MVP scope + cuts + must-haves.' },
      { av:'🎨', nm:'Landing Page Writer', sk:['writing','marketing'], persona:'Hired for: Write the landing page.\nDay-to-day: Hero + value + social proof + waitlist.' },
      { av:'📈', nm:'Analytics Setter', sk:['analysis','coding'], persona:'Hired for: Set up the right metrics.\nDay-to-day: 3 metrics that matter + dashboard.' },
    ],
    tags:['indie','founder'], demos:['Validate an idea: AI for solo founders'],
    price:0, uses:2840, rating:4.9, reviews:172, ribbon:'hot' },

  { av:'⚙️', slug:'team-ops-squad', nm:'Operations Squad', cat:'ops',
    goal:'SOPs + process docs + workflow automation + KPI dashboards.',
    desc:'SOPs + processes + automation + KPIs. Build the boring stuff that makes companies actually run.',
    members:[
      { av:'📋', nm:'SOP Writer', sk:['writing','planning'], persona:'Hired for: Document repeatable processes.\nDay-to-day: Step-by-step + owner + edge cases.' },
      { av:'🔁', nm:'Workflow Designer', sk:['planning','analysis'], persona:'Hired for: Map workflows.\nDay-to-day: Inputs → steps → outputs + bottleneck flag.' },
      { av:'📊', nm:'KPI Builder', sk:['analysis','planning'], persona:'Hired for: Define the right metrics.\nDay-to-day: Lead + lag indicators + dashboard structure.' },
    ],
    tags:['ops','process'], demos:['Document our customer onboarding process'],
    price:3900, uses:312, rating:4.8, reviews:24 },

  { av:'🤖', slug:'team-workflow-auto', nm:'Workflow Automator', cat:'ops',
    goal:'Find repeat tasks + design automation + write Zapier/Make playbooks.',
    desc:'Find repeats + design automation + write playbooks. Stop doing the same thing twice.',
    members:[
      { av:'🔍', nm:'Repeat Spotter', sk:['analysis','planning'], persona:'Hired for: Find repetitive work.\nDay-to-day: Time-tracking review + pattern detection.' },
      { av:'🤖', nm:'Automation Designer', sk:['planning','coding'], persona:'Hired for: Design the automation.\nDay-to-day: Trigger → steps → fallback → monitoring.' },
      { av:'📖', nm:'Playbook Writer', sk:['writing','planning'], persona:'Hired for: Write Zapier/Make playbooks.\nDay-to-day: Step-by-step setup with screenshots-as-text.' },
    ],
    tags:['automation','ops'], demos:['Automate our weekly status update'],
    price:2900, uses:412, rating:4.7, reviews:32 },

  { av:'🎯', slug:'team-okr-pod', nm:'OKR + Strategy Pod', cat:'ops',
    goal:'Strategy → OKRs → cascading initiatives → check-in cadence.',
    desc:'Strategy + OKRs + initiatives + check-ins. End the corporate-speak cycle.',
    members:[
      { av:'🧭', nm:'Strategist', sk:['planning','analysis'], persona:'Hired for: Define strategy.\nDay-to-day: Where to play + how to win + must-do moves.' },
      { av:'🎯', nm:'OKR Writer', sk:['planning','writing'], persona:'Hired for: Write meaningful OKRs.\nDay-to-day: Objective + 3 measurable KRs + check-in cadence.' },
      { av:'🚀', nm:'Initiative Cascader', sk:['planning','support'], persona:'Hired for: Cascade to teams.\nDay-to-day: Map company OKRs → team OKRs → personal goals.' },
    ],
    tags:['okr','strategy'], demos:['Set up annual OKRs for a 30-person company'],
    price:4900, uses:148, rating:4.8, reviews:12 },

  { av:'📈', slug:'team-finance-ops', nm:'Finance Ops Pod', cat:'ops',
    goal:'Monthly close + reporting + forecasting + budget tracking.',
    desc:'Monthly close + reporting + forecasting + budget. The non-CFO finance ops every startup needs.',
    members:[
      { av:'📚', nm:'Closer', sk:['analysis','planning'], persona:'Hired for: Run the monthly close.\nDay-to-day: Reconcile + accruals + journal + checklist.' },
      { av:'📊', nm:'Reporter', sk:['analysis','writing'], persona:'Hired for: Write the monthly report.\nDay-to-day: Revenue + costs + cash + commentary.' },
      { av:'🔮', nm:'Forecaster', sk:['analysis','planning'], persona:'Hired for: Forecast the next 12 months.\nDay-to-day: Driver-based model + scenarios + sanity checks.' },
    ],
    tags:['finance','ops'], demos:['Run the monthly close for a 5-person SaaS'],
    price:5900, uses:148, rating:4.8, reviews:12 },

  // ── Writing teams (4) ──
  { av:'🌍', slug:'team-translation-squad', nm:'Translation Squad', cat:'writing',
    goal:'JA↔EN translation that preserves brand voice + glossary management + QA.',
    desc:'Translate + brand voice + glossary + QA. A pod for product i18n that doesn\'t feel translated.',
    members:[
      { av:'🇯🇵', nm:'JA→EN Translator', sk:['translate','writing'], persona:'Hired for: Translate JA → EN.\nDay-to-day: Preserve nuance + brand voice + idiomatic English.' },
      { av:'🇺🇸', nm:'EN→JA Translator', sk:['translate','writing'], persona:'Hired for: Translate EN → JA.\nDay-to-day: 自然な日本語 + ブランドトーン + 用語統一.' },
      { av:'📖', nm:'Glossary Keeper', sk:['planning','writing'], persona:'Hired for: Maintain the glossary.\nDay-to-day: Term consistency + new-term proposals + change log.' },
    ],
    tags:['i18n','translation'], demos:['Translate this landing page to JA'],
    price:3900, uses:240, rating:4.8, reviews:18 },

  { av:'📝', slug:'team-newsroom', nm:'Newsroom Crew', cat:'writing',
    goal:'Story discovery + research + drafting + fact-checking + publishing.',
    desc:'Discovery + research + draft + fact-check + publish. A small newsroom that ships daily.',
    members:[
      { av:'🔍', nm:'Story Finder', sk:['research','idea'], persona:'Hired for: Find the day\'s story.\nDay-to-day: Scan signals + relevance + originality + angle.' },
      { av:'📰', nm:'Reporter', sk:['research','writing'], persona:'Hired for: Research and draft.\nDay-to-day: 5 sources minimum + balanced framing + clear lede.' },
      { av:'✏️', nm:'Editor', sk:['writing','analysis'], persona:'Hired for: Edit for clarity.\nDay-to-day: Tighten + sharpen + structure + headline.' },
      { av:'🔎', nm:'Fact-Checker', sk:['research','analysis'], persona:'Hired for: Verify claims.\nDay-to-day: Check every number + quote + attribution.' },
    ],
    tags:['journalism','writing'], demos:['Cover today\'s top startup story'],
    price:4900, uses:148, rating:4.9, reviews:12 },

  { av:'🎨', slug:'team-brand-voice', nm:'Brand Voice Studio', cat:'writing',
    goal:'Voice document + style guide + content audit + voice training material.',
    desc:'Voice doc + style guide + audit + training. Lock in brand voice across the company.',
    members:[
      { av:'🎤', nm:'Voice Definer', sk:['marketing','writing'], persona:'Hired for: Define the voice.\nDay-to-day: 3 traits, 3 we-don\'t-do, sample sentences.' },
      { av:'📖', nm:'Style Guide Writer', sk:['writing','planning'], persona:'Hired for: Write the style guide.\nDay-to-day: Grammar + format + terms + examples.' },
      { av:'🔍', nm:'Content Auditor', sk:['analysis','writing'], persona:'Hired for: Audit existing content.\nDay-to-day: On-voice or off-voice + suggested fixes.' },
    ],
    tags:['brand','voice'], demos:['Define brand voice for a fintech startup'],
    price:3900, uses:148, rating:4.9, reviews:12 },

  { av:'📜', slug:'team-press-release', nm:'Press Release Pod', cat:'writing',
    goal:'Find the angle + draft press release + pitch list + follow-up sequence.',
    desc:'Angle + release + list + pitches. Press releases that actually get coverage.',
    members:[
      { av:'🎯', nm:'Angle Finder', sk:['research','idea'], persona:'Hired for: Find the news angle.\nDay-to-day: Why now + why we + why anyone cares.' },
      { av:'📰', nm:'Release Writer', sk:['writing'], persona:'Hired for: Write the release.\nDay-to-day: Headline + lede + body + boilerplate.' },
      { av:'✍️', nm:'Pitch Writer', sk:['writing','marketing'], persona:'Hired for: Personalize pitches.\nDay-to-day: 10 journalists + 10 personalized pitches.' },
    ],
    tags:['press','marketing'], demos:['Write a press release for our Series A'],
    price:3900, uses:148, rating:4.7, reviews:12 },

  // ── Research teams (3) ──
  { av:'🔍', slug:'team-competitive-intel', nm:'Competitive Intel Crew', cat:'research',
    goal:'Track 10 competitors weekly: pricing changes + features + posts + hires.',
    desc:'Track 10 competitors. Pricing + features + posts + hires. Surface what matters every Friday.',
    members:[
      { av:'📊', nm:'Pricing Tracker', sk:['research','analysis'], persona:'Hired for: Track competitor pricing.\nDay-to-day: Weekly diffs + plan changes + signal.' },
      { av:'🚀', nm:'Feature Tracker', sk:['research','analysis'], persona:'Hired for: Track competitor product moves.\nDay-to-day: Changelog + blog + release notes diff.' },
      { av:'👥', nm:'Hires Tracker', sk:['research','analysis'], persona:'Hired for: Track who they\'re hiring.\nDay-to-day: LinkedIn + Wellfound + signal-fit hires.' },
    ],
    tags:['competitive','research'], demos:['Set up tracking for 10 fintech competitors'],
    price:4900, uses:148, rating:4.9, reviews:12 },

  { av:'📈', slug:'team-market-research', nm:'Market Research Crew', cat:'research',
    goal:'Market sizing + segmentation + customer interviews + opportunity matrix.',
    desc:'Sizing + segments + interviews + opportunities. Strategy-grade market research at startup speed.',
    members:[
      { av:'📊', nm:'Sizing Analyst', sk:['research','analysis'], persona:'Hired for: Size the market.\nDay-to-day: TAM/SAM/SOM with bottom-up + top-down.' },
      { av:'🎯', nm:'Segmenter', sk:['research','analysis'], persona:'Hired for: Define segments.\nDay-to-day: 3 segments × pain × budget × accessibility.' },
      { av:'💬', nm:'Interview Synthesizer', sk:['research','analysis','writing'], persona:'Hired for: Synthesize interviews.\nDay-to-day: Patterns + quotes + jobs-to-be-done.' },
    ],
    tags:['market','research'], demos:['Research the EV charging hardware market'],
    price:5900, uses:148, rating:4.9, reviews:12 },

  { av:'🧪', slug:'team-academic-research', nm:'Academic Research Crew', cat:'research',
    goal:'Literature review + paper summarization + citation management + draft writing.',
    desc:'Lit review + paper summaries + citations + draft. A pod for grad students and analysts.',
    members:[
      { av:'📚', nm:'Lit Reviewer', sk:['research','analysis'], persona:'Hired for: Run literature review.\nDay-to-day: Find + filter + cluster relevant papers.' },
      { av:'📖', nm:'Paper Summarizer', sk:['research','writing'], persona:'Hired for: Summarize papers.\nDay-to-day: Methodology + findings + limits + quotes.' },
      { av:'✍️', nm:'Draft Writer', sk:['writing','analysis'], persona:'Hired for: Help write the paper.\nDay-to-day: Section drafts + transitions + citation insertion.' },
    ],
    tags:['academic','research'], demos:['Lit review on RLHF in language models'],
    price:3900, uses:148, rating:4.8, reviews:12 },

  // ── Creative teams (4) ──
  { av:'🎬', slug:'team-video-production', nm:'Video Production Crew', cat:'other',
    goal:'Concept + script + shot list + edit notes + thumbnail copy.',
    desc:'Concept + script + shot list + edit + thumbnail. Run a YouTube channel like a small studio.',
    members:[
      { av:'💡', nm:'Concept Developer', sk:['idea','marketing'], persona:'Hired for: Develop video concepts.\nDay-to-day: Hook + arc + payoff + retention prediction.' },
      { av:'📝', nm:'Scriptwriter', sk:['writing','marketing'], persona:'Hired for: Write retention-tuned scripts.\nDay-to-day: 5s hook + tease + chapters + payoff + CTA.' },
      { av:'🎬', nm:'Shot Lister', sk:['planning','idea'], persona:'Hired for: Build shot lists.\nDay-to-day: Scene → shots → coverage + b-roll.' },
      { av:'🖼️', nm:'Thumbnail Copywriter', sk:['writing','marketing'], persona:'Hired for: Write thumbnail copy.\nDay-to-day: 3 options + hook variants + visual brief.' },
    ],
    tags:['video','youtube'], demos:['Plan an episode on the rise of AI agents'],
    price:4900, uses:148, rating:4.9, reviews:12 },

  { av:'🎙️', slug:'team-podcast-prod', nm:'Podcast Production Crew', cat:'other',
    goal:'Episode planning + guest research + show notes + clip suggestions + promo.',
    desc:'Plan + research guests + show notes + clips + promo. Run a podcast end-to-end.',
    members:[
      { av:'📅', nm:'Episode Planner', sk:['planning','idea'], persona:'Hired for: Plan the season.\nDay-to-day: Topics + guests + format + schedule.' },
      { av:'🔎', nm:'Guest Researcher', sk:['research'], persona:'Hired for: Research guests deeply.\nDay-to-day: Background + recent posts + sharp questions.' },
      { av:'📝', nm:'Show Notes Writer', sk:['writing'], persona:'Hired for: Write show notes.\nDay-to-day: Summary + chapters + links + memorable quotes.' },
      { av:'✂️', nm:'Clip Picker', sk:['analysis','marketing'], persona:'Hired for: Find shareable clips.\nDay-to-day: 3 clips × hook + caption + platform fit.' },
    ],
    tags:['podcast','content'], demos:['Plan a season on AI for solopreneurs'],
    price:4900, uses:148, rating:4.8, reviews:12 },

  { av:'🎨', slug:'team-brand-identity', nm:'Brand Identity Studio', cat:'marketing',
    goal:'Logo brief + color brief + typography brief + voice + brand guidelines.',
    desc:'Briefs + voice + guidelines. Get every designer + writer aligned on day one.',
    members:[
      { av:'🎨', nm:'Logo Briefer', sk:['idea','marketing'], persona:'Hired for: Brief logo design.\nDay-to-day: Concepts + restrictions + 3 directions.' },
      { av:'🎨', nm:'Color Briefer', sk:['idea','marketing'], persona:'Hired for: Pick the palette.\nDay-to-day: Primary + accent + neutral + accessibility.' },
      { av:'🔤', nm:'Type Briefer', sk:['idea','marketing'], persona:'Hired for: Pick typefaces.\nDay-to-day: Display + body + mono pairings + character.' },
      { av:'📖', nm:'Guidelines Writer', sk:['writing','planning'], persona:'Hired for: Write the brand book.\nDay-to-day: Voice + visual + dos/don\'ts + samples.' },
    ],
    tags:['brand','design'], demos:['Brief a brand for a sustainable activewear startup'],
    price:5900, uses:148, rating:4.9, reviews:12 },

  { av:'📚', slug:'team-story-studio', nm:'Story Studio', cat:'writing',
    goal:'Plot help + scene drafting + character development + dialogue polish.',
    desc:'Plot + scenes + characters + dialogue. A pod that assists fiction without auto-generating it.',
    members:[
      { av:'🧭', nm:'Plot Helper', sk:['idea','writing'], persona:'Hired for: Help plot.\nDay-to-day: Beat-sheet + tensions + payoffs + holes.' },
      { av:'✍️', nm:'Scene Drafter', sk:['writing','idea'], persona:'Hired for: Draft scenes.\nDay-to-day: Setting + action + dialogue + emotion arc.' },
      { av:'👤', nm:'Character Builder', sk:['idea','writing'], persona:'Hired for: Build characters.\nDay-to-day: Want + need + voice + 5-trait sketch.' },
      { av:'💬', nm:'Dialogue Polisher', sk:['writing','analysis'], persona:'Hired for: Polish dialogue.\nDay-to-day: Distinct voices + subtext + cuts.' },
    ],
    tags:['fiction','creative'], demos:['Help me plot a thriller chapter'],
    price:2400, uses:340, rating:4.8, reviews:24 },

  // ── More productivity / role teams ──
  { av:'🧑‍💼', slug:'team-hiring-squad', nm:'Hiring Loop Squad', cat:'ops',
    goal:'JD + sourcing + intro emails + interview kits + debrief synthesis.',
    desc:'JD + sourcing + emails + kits + debrief. Run a clean hiring loop without losing your week.',
    members:[
      { av:'📋', nm:'JD Writer', sk:['writing','planning'], persona:'Hired for: Write JDs.\nDay-to-day: Mission + must-haves + nice-to-haves + comp range.' },
      { av:'🔎', nm:'Sourcer', sk:['research'], persona:'Hired for: Source candidates.\nDay-to-day: LinkedIn + GitHub + portfolio + signal score.' },
      { av:'💌', nm:'Intro Emailer', sk:['writing','support'], persona:'Hired for: Write personalized intros.\nDay-to-day: Reference recent work + clear ask + low-friction call to action.' },
      { av:'🎤', nm:'Interview Kit Builder', sk:['planning','writing'], persona:'Hired for: Build interview kits.\nDay-to-day: Loop structure + questions + rubric + take-home.' },
      { av:'📊', nm:'Debrief Synthesizer', sk:['writing','analysis'], persona:'Hired for: Synthesize panel debriefs.\nDay-to-day: Per-panelist signal + recommendation + risks.' },
    ],
    tags:['hiring','hr'], demos:['Run an interview loop for a senior backend eng'],
    price:5900, uses:240, rating:4.8, reviews:18 },

  { av:'📞', slug:'team-meeting-pod', nm:'Meeting Pod', cat:'ops',
    goal:'Pre-meeting brief + facilitation script + note-taking + action items + follow-ups.',
    desc:'Brief + facilitate + take notes + action items + follow-ups. Meetings that produce.',
    members:[
      { av:'📋', nm:'Pre-meeting Briefer', sk:['planning','writing'], persona:'Hired for: Brief before meetings.\nDay-to-day: Goal + decisions to make + must-cover.' },
      { av:'🎤', nm:'Facilitation Scripter', sk:['planning','writing'], persona:'Hired for: Build facilitation scripts.\nDay-to-day: Open + topics + time-boxes + close.' },
      { av:'📝', nm:'Note Taker', sk:['writing','analysis'], persona:'Hired for: Take structured notes.\nDay-to-day: Summary + decisions + action items.' },
    ],
    tags:['meetings','ops'], demos:['Run an exec sync productively'],
    price:1900, uses:480, rating:4.7, reviews:36 },

  { av:'📥', slug:'team-inbox-pod', nm:'Inbox Pod', cat:'ops',
    goal:'Triage + reply drafts + scheduling + delegate suggestions + weekly review.',
    desc:'Triage + drafts + scheduling + delegate + review. Inbox zero, weekly.',
    members:[
      { av:'📥', nm:'Triager', sk:['support','analysis'], persona:'Hired for: Triage inbox.\nDay-to-day: Reply / Archive / Schedule / Delegate sort.' },
      { av:'✍️', nm:'Reply Drafter', sk:['writing','support'], persona:'Hired for: Draft replies.\nDay-to-day: 3 options each, tone-matched.' },
      { av:'📅', nm:'Scheduler', sk:['planning','support'], persona:'Hired for: Handle scheduling.\nDay-to-day: Find slots + send invites + reminders.' },
    ],
    tags:['email','productivity'], demos:['Triage today\'s 80 emails'],
    price:0, uses:1820, rating:4.7, reviews:128 },

  { av:'📊', slug:'team-data-storyteller', nm:'Data Storyteller Crew', cat:'research',
    goal:'Data exploration + chart suggestions + narrative draft + dashboard layout.',
    desc:'Explore + chart + narrate + lay out. Build data stories that decision-makers actually read.',
    members:[
      { av:'🕵️', nm:'Data Investigator', sk:['analysis','research'], persona:'Hired for: Find the story in data.\nDay-to-day: 3 patterns + the why behind each.' },
      { av:'📊', nm:'Chart Designer', sk:['analysis','idea'], persona:'Hired for: Suggest charts.\nDay-to-day: Right chart per pattern + color/legend tips.' },
      { av:'✍️', nm:'Narrator', sk:['writing','analysis'], persona:'Hired for: Write the narrative.\nDay-to-day: Headline + 3 sections + so-what.' },
    ],
    tags:['data','analysis'], demos:['Tell the story in this Stripe revenue export'],
    price:3900, uses:212, rating:4.8, reviews:18 },
];

// ── Builders ──
function _buildSeedAgent(spec, idx){
  const now = new Date().toISOString();
  const persona = `Hired for: ${spec.hire}\nDay-to-day: ${spec.duties}`;
  const skills = spec.sk.slice(0, 3);
  const listingId = 'ls_seed_' + spec.slug;
  return {
    id: 'ag_seed_' + spec.slug,
    avatar: spec.av,
    name: spec.nm,
    skills,
    persona,
    chrome_enabled: false,
    sheets_enabled: false,
    extension_enabled: false,
    model: 'sonnet',
    history: [],
    created_at: now,
    is_seed: true,
    marketplace: {
      is_listed: true,
      listing_id: listingId,
      title: spec.nm,
      description: spec.desc,
      category: spec.cat,
      tags: spec.tags || [],
      demo_prompts: spec.demos || [],
      visibility: 'public',
      price_jpy: spec.price || 0,
      status: 'live',
      listed_at: now,
      updated_at: now,
      uses_count: spec.uses || 0,
      purchases_count: Math.floor((spec.uses || 0) / 4),
      rating_avg: spec.rating || 0,
      rating_count: spec.reviews || 0,
      reviews: [],
    },
  };
}

function _buildSeedTeam(spec, idx){
  const now = new Date().toISOString();
  const teamId = 'ag_seed_' + spec.slug;
  const listingId = 'ls_seed_' + spec.slug;
  // Build member agents
  const members = (spec.members||[]).map((m, i) => ({
    id: teamId + '_m' + i,
    avatar: m.av,
    name: m.nm,
    skills: m.sk.slice(0, 3),
    persona: m.persona,
    chrome_enabled: false,
    sheets_enabled: false,
    extension_enabled: false,
    model: 'sonnet',
    history: [],
    created_at: now,
    is_seed: true,
    team_origin: { team_id: teamId, seed: true },
  }));
  // Build the team group
  const group = {
    id: teamId,
    avatar: spec.av,
    name: spec.nm,
    skills: ['planning'],
    persona: '',
    is_group: true,
    is_team: true,
    team_template_id: 'seed',
    team_goal: spec.goal,
    lang: 'en',
    host_id: 'sys_marketplace_seed',
    members: [{
      user_id: 'sys_marketplace_seed',
      name: 'MY AI AGENT',
      email: 'curated@myaiagents.agency',
      joined_at: now,
      role: 'host',
      notify_pref: 'all',
    }],
    team_member_agent_ids: members.map(m => m.id),
    ai_auto_respond: false,
    created_at: now,
    updated_at: now,
    is_seed: true,
    history: [],
    marketplace: {
      is_listed: true,
      listing_id: listingId,
      title: spec.nm,
      description: spec.desc,
      category: spec.cat,
      tags: spec.tags || [],
      demo_prompts: spec.demos || [],
      visibility: 'public',
      price_jpy: spec.price || 0,
      status: 'live',
      listed_at: now,
      updated_at: now,
      uses_count: spec.uses || 0,
      purchases_count: Math.floor((spec.uses || 0) / 4),
      rating_avg: spec.rating || 0,
      rating_count: spec.reviews || 0,
      reviews: [],
    },
  };
  return { members, group };
}

module.exports = {
  SEED_AGENTS: SEED_AGENTS.slice(0, 50),  // exactly 50 solo listings
  SEED_TEAMS: SEED_TEAMS.slice(0, 50),    // exactly 50 team listings
  buildSeedAgent: _buildSeedAgent,
  buildSeedTeam: _buildSeedTeam,
};
